// Generated by gencpp from file test_pkg/JudgeServiceMsgRequest.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_JUDGESERVICEMSGREQUEST_H
#define TEST_PKG_MESSAGE_JUDGESERVICEMSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test_pkg
{
template <class ContainerAllocator>
struct JudgeServiceMsgRequest_
{
  typedef JudgeServiceMsgRequest_<ContainerAllocator> Type;

  JudgeServiceMsgRequest_()
    : num(0.0)  {
    }
  JudgeServiceMsgRequest_(const ContainerAllocator& _alloc)
    : num(0.0)  {
  (void)_alloc;
    }



   typedef float _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JudgeServiceMsgRequest_

typedef ::test_pkg::JudgeServiceMsgRequest_<std::allocator<void> > JudgeServiceMsgRequest;

typedef boost::shared_ptr< ::test_pkg::JudgeServiceMsgRequest > JudgeServiceMsgRequestPtr;
typedef boost::shared_ptr< ::test_pkg::JudgeServiceMsgRequest const> JudgeServiceMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace test_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'test_pkg': ['/home/lhz/tutorial_2019/tasks/week3/test_project/src/test_pkg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f884e6aaf5401e90c303ed6b729a37f";
  }

  static const char* value(const ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f884e6aaf5401e9ULL;
  static const uint64_t static_value2 = 0x0c303ed6b729a37fULL;
};

template<class ContainerAllocator>
struct DataType< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test_pkg/JudgeServiceMsgRequest";
  }

  static const char* value(const ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 num\n"
;
  }

  static const char* value(const ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JudgeServiceMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test_pkg::JudgeServiceMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<float>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_PKG_MESSAGE_JUDGESERVICEMSGREQUEST_H
