// Generated by gencpp from file test_pkg/JudgeServiceMsg.msg
// DO NOT EDIT!


#ifndef TEST_PKG_MESSAGE_JUDGESERVICEMSG_H
#define TEST_PKG_MESSAGE_JUDGESERVICEMSG_H

#include <ros/service_traits.h>


#include <test_pkg/JudgeServiceMsgRequest.h>
#include <test_pkg/JudgeServiceMsgResponse.h>


namespace test_pkg
{

struct JudgeServiceMsg
{

typedef JudgeServiceMsgRequest Request;
typedef JudgeServiceMsgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JudgeServiceMsg
} // namespace test_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test_pkg::JudgeServiceMsg > {
  static const char* value()
  {
    return "8bc6b2e4853471d795c6111400fa59fc";
  }

  static const char* value(const ::test_pkg::JudgeServiceMsg&) { return value(); }
};

template<>
struct DataType< ::test_pkg::JudgeServiceMsg > {
  static const char* value()
  {
    return "test_pkg/JudgeServiceMsg";
  }

  static const char* value(const ::test_pkg::JudgeServiceMsg&) { return value(); }
};


// service_traits::MD5Sum< ::test_pkg::JudgeServiceMsgRequest> should match 
// service_traits::MD5Sum< ::test_pkg::JudgeServiceMsg > 
template<>
struct MD5Sum< ::test_pkg::JudgeServiceMsgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test_pkg::JudgeServiceMsg >::value();
  }
  static const char* value(const ::test_pkg::JudgeServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_pkg::JudgeServiceMsgRequest> should match 
// service_traits::DataType< ::test_pkg::JudgeServiceMsg > 
template<>
struct DataType< ::test_pkg::JudgeServiceMsgRequest>
{
  static const char* value()
  {
    return DataType< ::test_pkg::JudgeServiceMsg >::value();
  }
  static const char* value(const ::test_pkg::JudgeServiceMsgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test_pkg::JudgeServiceMsgResponse> should match 
// service_traits::MD5Sum< ::test_pkg::JudgeServiceMsg > 
template<>
struct MD5Sum< ::test_pkg::JudgeServiceMsgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test_pkg::JudgeServiceMsg >::value();
  }
  static const char* value(const ::test_pkg::JudgeServiceMsgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test_pkg::JudgeServiceMsgResponse> should match 
// service_traits::DataType< ::test_pkg::JudgeServiceMsg > 
template<>
struct DataType< ::test_pkg::JudgeServiceMsgResponse>
{
  static const char* value()
  {
    return DataType< ::test_pkg::JudgeServiceMsg >::value();
  }
  static const char* value(const ::test_pkg::JudgeServiceMsgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_PKG_MESSAGE_JUDGESERVICEMSG_H
