// Generated by gencpp from file pns/def_message.msg
// DO NOT EDIT!


#ifndef PNS_MESSAGE_DEF_MESSAGE_H
#define PNS_MESSAGE_DEF_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pns
{
template <class ContainerAllocator>
struct def_message_
{
  typedef def_message_<ContainerAllocator> Type;

  def_message_()
    : a(0)
    , b(0)
    , c(0)  {
    }
  def_message_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , c(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;

   typedef int64_t _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::pns::def_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pns::def_message_<ContainerAllocator> const> ConstPtr;

}; // struct def_message_

typedef ::pns::def_message_<std::allocator<void> > def_message;

typedef boost::shared_ptr< ::pns::def_message > def_messagePtr;
typedef boost::shared_ptr< ::pns::def_message const> def_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pns::def_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pns::def_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pns

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pns': ['/home/lomgahong/pub_n_sub/src/pns/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pns::def_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pns::def_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pns::def_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pns::def_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pns::def_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pns::def_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pns::def_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8559b52d432bccd240703f31aeca517";
  }

  static const char* value(const ::pns::def_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8559b52d432bccdULL;
  static const uint64_t static_value2 = 0x240703f31aeca517ULL;
};

template<class ContainerAllocator>
struct DataType< ::pns::def_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pns/def_message";
  }

  static const char* value(const ::pns::def_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pns::def_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
"int64 c\n"
;
  }

  static const char* value(const ::pns::def_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pns::def_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct def_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pns::def_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pns::def_message_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<int64_t>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PNS_MESSAGE_DEF_MESSAGE_H
