// Generated by gencpp from file judge/def_message.msg
// DO NOT EDIT!


#ifndef JUDGE_MESSAGE_DEF_MESSAGE_H
#define JUDGE_MESSAGE_DEF_MESSAGE_H

#include <ros/service_traits.h>


#include <judge/def_messageRequest.h>
#include <judge/def_messageResponse.h>


namespace judge
{

struct def_message
{

typedef def_messageRequest Request;
typedef def_messageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct def_message
} // namespace judge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::judge::def_message > {
  static const char* value()
  {
    return "42c1fb09fc6033803973422ff2802e4e";
  }

  static const char* value(const ::judge::def_message&) { return value(); }
};

template<>
struct DataType< ::judge::def_message > {
  static const char* value()
  {
    return "judge/def_message";
  }

  static const char* value(const ::judge::def_message&) { return value(); }
};


// service_traits::MD5Sum< ::judge::def_messageRequest> should match 
// service_traits::MD5Sum< ::judge::def_message > 
template<>
struct MD5Sum< ::judge::def_messageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::judge::def_message >::value();
  }
  static const char* value(const ::judge::def_messageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::judge::def_messageRequest> should match 
// service_traits::DataType< ::judge::def_message > 
template<>
struct DataType< ::judge::def_messageRequest>
{
  static const char* value()
  {
    return DataType< ::judge::def_message >::value();
  }
  static const char* value(const ::judge::def_messageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::judge::def_messageResponse> should match 
// service_traits::MD5Sum< ::judge::def_message > 
template<>
struct MD5Sum< ::judge::def_messageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::judge::def_message >::value();
  }
  static const char* value(const ::judge::def_messageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::judge::def_messageResponse> should match 
// service_traits::DataType< ::judge::def_message > 
template<>
struct DataType< ::judge::def_messageResponse>
{
  static const char* value()
  {
    return DataType< ::judge::def_message >::value();
  }
  static const char* value(const ::judge::def_messageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JUDGE_MESSAGE_DEF_MESSAGE_H
