// Generated by gencpp from file judge/def_messageRequest.msg
// DO NOT EDIT!


#ifndef JUDGE_MESSAGE_DEF_MESSAGEREQUEST_H
#define JUDGE_MESSAGE_DEF_MESSAGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace judge
{
template <class ContainerAllocator>
struct def_messageRequest_
{
  typedef def_messageRequest_<ContainerAllocator> Type;

  def_messageRequest_()
    : ask(0.0)  {
    }
  def_messageRequest_(const ContainerAllocator& _alloc)
    : ask(0.0)  {
  (void)_alloc;
    }



   typedef double _ask_type;
  _ask_type ask;





  typedef boost::shared_ptr< ::judge::def_messageRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::judge::def_messageRequest_<ContainerAllocator> const> ConstPtr;

}; // struct def_messageRequest_

typedef ::judge::def_messageRequest_<std::allocator<void> > def_messageRequest;

typedef boost::shared_ptr< ::judge::def_messageRequest > def_messageRequestPtr;
typedef boost::shared_ptr< ::judge::def_messageRequest const> def_messageRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::judge::def_messageRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::judge::def_messageRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace judge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::judge::def_messageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::judge::def_messageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::judge::def_messageRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::judge::def_messageRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::judge::def_messageRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::judge::def_messageRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::judge::def_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ddbe15febb103006edb58c3b0b204bed";
  }

  static const char* value(const ::judge::def_messageRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xddbe15febb103006ULL;
  static const uint64_t static_value2 = 0xedb58c3b0b204bedULL;
};

template<class ContainerAllocator>
struct DataType< ::judge::def_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "judge/def_messageRequest";
  }

  static const char* value(const ::judge::def_messageRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::judge::def_messageRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ask\n"
;
  }

  static const char* value(const ::judge::def_messageRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::judge::def_messageRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ask);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct def_messageRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::judge::def_messageRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::judge::def_messageRequest_<ContainerAllocator>& v)
  {
    s << indent << "ask: ";
    Printer<double>::stream(s, indent + "  ", v.ask);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JUDGE_MESSAGE_DEF_MESSAGEREQUEST_H
