LIB_PATH = /usr/local/lib
INC_PATH = include/:/usr/local/include/opencv4/
LIB_FILE = -lopencv_highgui -lopencv_imgproc -lopencv_imgcodecs -lopencv_core -lopencv_videoio
scbg5: scbg5.cpp
	g++ -O2	scbg5.cpp ${LIB_FILE} -o scbg5 -I${INC_PATH}
